/*
 *
 * CitySelect constants
 *
 */

export const SELECT_CITY = 'SELECT_CITY';
export const WEATHER_FETCH_SUCCEEDED = 'WEATHER_FETCH_SUCCEEDED';
export const WEATHER_FETCH_FAILED = 'WEATHER_FETCH_FAILED';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';

export const FORECAST_FETCH_SUCCEEDED = 'FORECAST_FETCH_SUCCEEDED';
export const FORECAST_FETCH_FAILED = 'FORECAST_FETCH_FAILED';
